version: '3.8'
services:
  cxr-api:
    build:
      context: .
      dockerfile: service/Dockerfile
    image: cxr-api:latest
    ports:
      - "8080:8080"
    environment:
      - MODEL_PATH=/app/runs_resnet50/resnet50_pneumonia_traced.pt
      - IMG_SIZE=224
      - THRESHOLD=0.20
    volumes:
      - ./service/runs_resnet50:/app/runs_resnet50:ro
